import { SpatialTelemetry } from "types/Telemetry";
import { CameraControlsState } from "types/Camera";


export const DEFAULT_CAMERA_CONTROLS: CameraControlsState = {
  torchSupported: false,
  torchOn: false,
  zoomSupported: false,
  zoomMin: 1,
  zoomMax: 1,
  zoomStep: 0.1,
  zoomValue: 1,
  focusSupported: false,
  focusModes: [],
  focusMode: '',
};
export const DEFAULT_TELEMETRY: SpatialTelemetry = {
  mode: 'viewer',
  locationLock: false,
  recordingActive: false,
  lat: null,
  lon: null,
  altitude: null,
  accuracy: null,
  altitudeAccuracy: null,
  gpsHeading: null,
  speed: null,
  compassHeading: null,
  compassSource: 'none',
  compassAbsolute: false,
  alpha: null,
  beta: null,
  gamma: null,
  accelerationX: null,
  accelerationY: null,
  accelerationZ: null,
  accelerationGravityX: null,
  accelerationGravityY: null,
  accelerationGravityZ: null,
  rotationAlpha: null,
  rotationBeta: null,
  rotationGamma: null,
  motionInterval: null,
  targetKind: 'none',
  targetX: null,
  targetY: null,
  targetZ: null,
  likelyIndoors: false,
  likelyOutdoors: true,
};